language: python

cache: pip

python:
  - "3.5"

services:
  - postgresql

install: "pip install -q -r requirements.txt"

jobs:
  include:
    - stage: lint
      script: flake8 ./src/spz
    - stage: test
      env:
          - SPZ_CFG_FILE=../../../conf/spz/travis.cfg
      before_script:
          - psql -c 'create database spz;' -U postgres
          - cd ./src/spz
          - YES_I_KNOW_THAT_WORLD_ENDS_NOW=1 python -m util.init_db
          - python -m util.build_assets
          - gzip --keep --recursive --force --best spz/static
      script: pytest .
