version: '2'
services:
    app:
        environment:
            - SPZ_CFG_FILE=production.cfg
            - VIRTUAL_HOST=anmeldung.spz.kit.edu
            - LETSENCRYPT_HOST=anmeldung.spz.kit.edu
            - VIRTUAL_PROTO=uwsgi
            - VIRTUAL_PORT=3031
    postgres:
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    mail:
        image: spzsignup/opensmtpd:6.0.3p1
        volumes:
            - ./conf/mail/smtpd.conf:/etc/smtpd.conf
    nginx:
        image: jwilder/nginx-proxy
        container_name: nginx
        restart: unless-stopped
        volumes:
            - cache_nginx:/var/cache/nginx
            - data_static:/static:ro
            - /etc/nginx/certs
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - front
        links:
            - app
        ports:
            - "80:80"
            - "443:443"
    nginx-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-letsencrypt
        restart: unless-stopped
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/acme.sh
        environment:
            DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL}
        depends_on:
            - nginx
    pg-dump:
        image: spzsignup/docker-postgres-backup:latest
        container_name: pg-dump
        restart: unless-stopped
        environment:
            CRON_TIME: 0 * * * *
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: spz
            MAX_BACKUPS: 200
            INIT_BACKUP: 'true'
        volumes:
            - backup:/backup
        networks:
            - back
        links:
            - postgres
    backup:
        image: southclaws/restic-robot:latest
        container_name: backup
        restart: unless-stopped
        environment:
            # once every hour (10 minutes past)
            SCHEDULE: 0 10 * * * *
            RESTIC_REPOSITORY: 'b2:spz-backup'
            RESTIC_ARGS: /data
            RUN_ON_BOOT: 'true'
            B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
            B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD}
        volumes:
            - backup:/data/
