version: '2'
services:
    app:
        restart: unless-stopped
        environment:
            SPZ_CFG_FILE: production.cfg
            VIRTUAL_HOST: ${HOST:?}
            LETSENCRYPT_HOST: ${HOST:?}
        volumes:
            - ./conf/app.conf:/home/spz/code/instance/production.cfg:ro
    celery_beat:
        restart: unless-stopped
        environment:
            SPZ_CFG_FILE: production.cfg
        volumes:
            - ./conf/app.conf:/home/spz/code/instance/production.cfg:ro
    celery_default:
        restart: unless-stopped
        environment:
            SPZ_CFG_FILE: production.cfg
        volumes:
            - ./conf/app.conf:/home/spz/code/instance/production.cfg:ro
    celery_slow_mails:
        restart: unless-stopped
        environment:
            SPZ_CFG_FILE: production.cfg
        volumes:
            - ./conf/app.conf:/home/spz/code/instance/production.cfg:ro
    postgres:
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
        volumes:
            - ./conf/postgresql.conf:/var/lib/postgresql/postgresql.conf:ro
    mail:
        restart: unless-stopped
        image: spzsignup/opensmtpd:6.8.0p2
        volumes:
            - ./conf/smtpd.conf:/etc/smtpd.conf
    nginx:
        restart: unless-stopped
        volumes:
            - /etc/nginx/certs
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
        ports:
            - "80:80"
            - "443:443"
    nginx-letsencrypt:
        restart: unless-stopped
        image: jrcs/letsencrypt-nginx-proxy-companion:latest
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/acme.sh
        environment:
            DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL:?}
        depends_on:
            - nginx
    pg-dump:
        restart: unless-stopped
        image: spzsignup/docker-postgres-backup:latest
        environment:
            CRON_TIME: 0 * * * *
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
            POSTGRES_DB: spz
            MAX_BACKUPS: 200
            INIT_BACKUP: 'true'
        volumes:
            - backup:/backup
        networks:
            - back
        links:
            - postgres
    backup:
        restart: unless-stopped
        image: southclaws/restic-robot:latest
        environment:
            SCHEDULE: 0 10 * * * *
            RESTIC_REPOSITORY: 'b2:spz-backup'
            RESTIC_ARGS: /data
            RUN_ON_BOOT: 'true'
            B2_ACCOUNT_ID: ${B2_ACCOUNT_ID:?}
            B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY:?}
            RESTIC_PASSWORD: ${RESTIC_PASSWORD:?}
        volumes:
            - backup:/data

volumes:
    backup: {}
