version: '2'
services:
    app:
        image: spzsignup/app:latest
        command: uwsgi --ini uwsgi.ini --workers 8 --threads 4
        volumes:
            - ./conf/spz:/home/spz/config:ro
            - data_static:/home/spz/code/spz/static:rw
        tmpfs:
            - /tmp
        read_only: true
        environment:
            - MAIL_PORT=tcp://mail:25
            - POSTGRES_PORT=tcp://postgres:5432
            - REDIS_PORT=tcp://redis:6379
        links:
            - mail
            - postgres
            - redis
        networks:
            - front
            - back
        restart: unless-stopped
    celery_beat:
        image: spzsignup/app:latest
        command: celery --app=spz.tasks.cel beat --schedule=/state/celerybeat-schedule --pidfile=/tmp/celerybeat.pid --loglevel=INFO
        volumes_from:
            - app
        tmpfs:
            - /tmp
        read_only: true
        environment:
            - MAIL_PORT=tcp://mail:25
            - POSTGRES_PORT=tcp://postgres:5432
            - REDIS_PORT=tcp://redis:6379
        links:
            - mail
            - postgres
            - redis
        networks:
            - back
        restart: unless-stopped
    celery_default:
        image: spzsignup/app:latest
        command: celery --app=spz.tasks.cel worker --queues=default --loglevel=INFO --concurrency 1
        volumes_from:
            - app
        tmpfs:
            - /tmp
        read_only: true
        environment:
            - MAIL_PORT=tcp://mail:25
            - POSTGRES_PORT=tcp://postgres:5432
            - REDIS_PORT=tcp://redis:6379
        links:
            - mail
            - postgres
            - redis
        networks:
            - back
        restart: unless-stopped
    celery_slow_mails:
        image: spzsignup/app:latest
        command: celery --app=spz.tasks.cel worker --queue=slow_mails --loglevel=INFO --concurrency 1
        volumes_from:
            - app
        tmpfs:
            - /tmp
        read_only: true
        environment:
            - MAIL_PORT=tcp://mail:25
            - POSTGRES_PORT=tcp://postgres:5432
            - REDIS_PORT=tcp://redis:6379
        links:
            - mail
            - postgres
            - redis
        networks:
            - back
        restart: unless-stopped
    redis:
        image: redis:6.2
        command: redis-server --appendonly yes
        volumes:
            - data_redis:/data
        read_only: true
        networks:
            - back
        restart: unless-stopped
    postgres:
        image: postgres:13.2
        volumes:
            - ./conf/database/initdb:/docker-entrypoint-initdb.d:ro
            - ./conf/database/postgresql.conf:/var/lib/postgresql/postgresql.conf:ro
            - data_postgres:/var/lib/postgresql/data
        tmpfs:
            - /run/postgresql
            - /tmp
        read_only: true
        environment:
            - POSTGRES_PASSWORD
        networks:
            - back
        restart: unless-stopped
    mail:
        volumes:
            - state_mail:/var/spool
        tmpfs:
            - /run
            - /tmp
        networks:
            - back
        restart: unless-stopped

volumes:
    backup: {}
    cache_nginx: {}
    data_postgres: {}
    data_redis: {}
    data_static: {}
    state_mail: {}
    state_spz: {}
networks:
    front: {}
    back: {}
