version: '2'
services:
    uwsgi:
        ports:
            - "127.0.0.1:3031:3031"
        volumes:
            - ./src/spz/spz:/home/spz/code/spz:ro
            - ./src/spz/util:/home/spz/code/util:ro
        environment:
            - FLASK_ENV=development
    celery_beat:
        environment:
            - FLASK_ENV=development
    celery_default:
        command: celery --app=spz.tasks.cel worker --queues=default --loglevel=INFO --concurrency 1
        environment:
            - FLASK_ENV=development
    celery_slow_mails:
        command: celery --app=spz.tasks.cel worker --queue=slow_mails --loglevel=INFO --concurrency 1
        environment:
            - FLASK_ENV=development
    redis:
        ports:
            - "127.0.0.1:26379:6379"
    postgres:
        ports:
            - "127.0.0.1:25432:5432"
    mail:
        image: djfarrelly/maildev:1.1.0
        ports:
            - "127.0.0.1:8080:80"
    nginx:
        ports:
            - "127.0.0.1:8081:80"
            - "127.0.0.1:443:443"
