version: '2'

x-spzsignup-app: &spzsignup-app
    image: spzsignup/app:latest
    tmpfs:
        - /tmp
    links:
        - mail
        - redis
        - postgres
    networks:
        - back
    read_only: true

services:
    app:
        <<: *spzsignup-app
        command: uwsgi --ini uwsgi.ini --workers 8 --threads 4
        environment:
            VIRTUAL_PROTO: uwsgi
            VIRTUAL_PORT: 3031
            SPZ_CFG_FILE: production.cfg
        volumes:
            - ./resource:/home/spz/code/spz/resource:ro
            - data_static:/home/spz/code/spz/static:rw
            - ./conf/app.conf:/home/spz/code/instance/production.cfg:ro
        networks:
            - front
            - back
    celery_beat:
        <<: *spzsignup-app
        command: celery --app=spz.tasks.cel beat --schedule=/state/celerybeat-schedule --pidfile=/tmp/celerybeat.pid --loglevel=INFO
        environment:
            SPZ_CFG_FILE: production.cfg
        volumes:
            - state_celery:/state
            - ./conf/app.conf:/home/spz/code/instance/production.cfg:ro
    celery_default:
        <<: *spzsignup-app
        command: celery --app=spz.tasks.cel worker --queues=default --loglevel=INFO --concurrency 1
        environment:
            SPZ_CFG_FILE: production.cfg
        volumes:
            - ./conf/app.conf:/home/spz/code/instance/production.cfg:ro
    celery_slow_mails:
        <<: *spzsignup-app
        command: celery --app=spz.tasks.cel worker --queues=slow_mails --loglevel=INFO --concurrency 1
        environment:
            SPZ_CFG_FILE: production.cfg
        volumes:
            - ./conf/app.conf:/home/spz/code/instance/production.cfg:ro
    redis:
        image: redis:6.2
        command: redis-server --appendonly yes
        volumes:
            - data_redis:/data
        networks:
            - back
        read_only: true
    postgres:
        image: postgres:13.2
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d:ro
            - data_postgres:/var/lib/postgresql/data
        tmpfs:
            - /run
            - /tmp
        networks:
            - back
        read_only: true
    mail:
        volumes:
            - state_mail:/var/spool
        tmpfs:
            - /run
            - /tmp
        networks:
            - back
        read_only: true
    nginx:
        image: nginxproxy/nginx-proxy:1.6
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - data_static:/static:ro
            - cache_nginx:/var/cache/nginx
            - state_nginx:/etc/nginx
        tmpfs:
            - /run
            - /tmp
        networks:
            - front
        links:
            - app
        read_only: true

volumes:
    cache_nginx: {}
    data_postgres: {}
    data_redis: {}
    data_static: {}
    state_mail: {}
    state_nginx: {}
    state_celery: {}

networks:
    front: {}
    back: {}
