version: '2'
services:
    app:
        environment:
            FLASK_ENV: development
            VIRTUAL_HOST: localhost
    celery_beat:
        environment:
            FLASK_ENV: development
    celery_default:
        environment:
            FLASK_ENV: development
    celery_slow_mails:
        environment:
            FLASK_ENV: development
    mail:
        image: maildev/maildev:1.1.0
        ports:
            - "8080:80"
    postgres:
        environment:
            POSTGRES_PASSWORD: dev-password
    nginx:
        volumes:
            - ./ssl/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
            - ./ssl/main.crt+chain.pem:/etc/nginx/certs/localhost.crt:ro
            - ./ssl/main.key.pem:/etc/nginx/certs/localhost.key:ro
        ports:
            - "81:80"
            - "443:443"
