#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from datetime import datetime
from uuid import uuid4

from flask import json
from jsonschema import validate, ValidationError, SchemaError

from spz import app, db
from spz.models import *  # Keep this import, otherwise the create_all call won't any models at all


def validate_resources():
    resources = ('degrees', 'origins', 'courses', 'degrees', 'graduations')

    for fname in resources:
        with app.open_resource('resource/{0}.json'.format(fname)) as fd_json, \
             app.open_resource('resource/{0}.schema'.format(fname)) as fd_schema:

            res_json = json.load(fd_json)
            res_schema = json.load(fd_schema)

            validate(res_json, res_schema)


def insert_resources():
    with app.open_resource('resource/degrees.json') as fd:
        res = json.load(fd)

        for degree in res["degrees"]:
            db.session.add(Degree(degree))

    with app.open_resource('resource/graduations.json') as fd:
        res = json.load(fd)

        for graduation in res["graduations"]:
            db.session.add(Graduation(graduation))

    with app.open_resource('resource/origins.json') as fd:
        res = json.load(fd)

        for origin in res["origins"]:
            db.session.add(Origin(origin))

    with app.open_resource('resource/courses.json') as fd:
        res = json.load(fd)

        for language in res["languages"]:
            ref_lang = Language(language["name"], language["reply_to"],
                                datetime.strptime(language["signup_begin_iso_utc"], "%Y-%m-%dT%H:%M:%S.Z"),  # ISO 8601 -- better way to parse this?
                                datetime.strptime(language["signup_end_iso_utc"], "%Y-%m-%dT%H:%M:%S.Z"))  # see also Jsonschema RFC, date-time

            for course in language["courses"]:
                for alt in course["alternative"]:
                    db.session.add(Course(ref_lang, level=course["level"], alternative=alt, limit=course["limit"],
                                          price=course["price"], rating_lowest=course["rating_lowest"],
                                          rating_highest=course["rating_highest"]))

    db.session.commit()


# Has to be done only once, to initialize the database;
# do not use this in regular code

if __name__ == '__main__':
    try:
        validate_resources()  # Strong exception safety guarantee
    except (ValidationError, SchemaError) as e:
        print(e)  # Stacktrace does not contain any useful information
        sys.exit()

    # Request polite confirmation
    token = uuid4().get_hex()[:5]  # repeat random token of arbitrary length
    user_in = raw_input('Create and drop tables using {0}\nConfirm by repeating the following token\n{1}\n'.format(db, token))

    if token == user_in:
        db.drop_all()
        db.create_all()
        insert_resources()

        print('Import OK.')
    else:
        print('Aborting: {0} did not match token {1}'.format(user_in, token))


# vim: set tabstop=4 shiftwidth=4 expandtab:
