# -*- coding: utf-8 -*-

from datetime import timedelta

# production configuration that differs from default (spz/config.py) goes here

SECRET_KEY = 'dev-secret'
TOKEN_SECRET_KEY = 'dev-secret'
ARGON2_SALT = 'dev-secret'

DB_DB = 'spz'
DB_DRIVER = 'postgresql'
DB_HOST = 'postgres'
DB_USER = 'postgres'
DB_PW = 'dev-password'

SQLALCHEMY_DATABASE_URI = '{driver}://{user}:{pw}@{host}/{db}'.format(
    db=DB_DB,
    driver=DB_DRIVER,
    host=DB_HOST,
    pw=DB_PW,
    user=DB_USER
)

SEMESTER_NAME = 'Testsemester 202X'
EXAM_DATE = '17.02.202X'
SEMESTER_NAME_SHORT = 'TS 202X'

WEEKS = '13'


REPLY_TO = [
    'info@spz.kit.edu',
    'englisch@spz.kit.edu',
    'franzoesisch@spz.kit.edu',
    'spanisch@spz.kit.edu',
]

# The time period the applicants can signoff themselves
SELF_SIGNOFF_PERIOD = timedelta(days=7)
# afterwards, the automatic restock system kicks in;
# some time later, the RND process is finished and we continue with FCFS (in case there are empty slots)
RANDOM_WINDOW_CLOSED_FOR = timedelta(hours=36)

# limit for global amount of attendances; this does not affect attendances for courses that are already
# done "now"; e.g. intensive
MAX_ATTENDANCES = 2

# maximum size, a 'short' waiting list may have
SHORT_WAITING_LIST = 5

# maximum amount of vacancies, a course with 'little vacancies' may have
LITTLE_VACANCIES = 5

# file directory (for xls grade sheets)
FILE_DIR = '/home/spz/code/spz/files'

# default column to read in the grade from the xls sheet (check template courselist-enhanced.xlsx)
DEFAULT_TEMPLATE_NAME = "Excel mit Zusatzfunktionen (eine Datei pro Kurs)"
DEFAULT_GRADE_COLUMN = 'E'
DEFAULT_MAIL_COLUMN = 'H'
DEFAULT_ECTS_COLUMN = 'I'
DEFAULT_HIDE_GRADE_COLUMN = 'H'
DEFAULT_TS_REQUESTED_COLUMN = 'J'
DEFAULT_TS_RECEIVED_COLUMN = 'L'
MAX_ROWS = 35

# data for ilias sync
ILIAS_URL = 'https://pilot.ilias.studium.kit.edu/'
ILIAS_USERNAME = 'soap_spz'
ILIAS_PASSWORD = 'mysecretpassword'
ILIAS_REFID = '123'

CLIENT_ID = 'myclientid'
CLIENT_SECRET = 'myclientsecret'
