#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse

from spz import app


# Do not try to import this, instead run it like:
# python runserver.py


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Starts a local development server running the spz application')

    parser.add_argument('-H', '--host', dest='host', type=str, default='127.0.0.1',
                      help='Host/Interface that is used during the binding process.')
    parser.add_argument('-P', '--port', dest='port', type=int, default=8080,
                      help='Port that is used during the binding process.')

    mode = parser.add_mutually_exclusive_group(required=False)
    mode.add_argument('-p', '--profile', dest='profiling', action="store_true",
                      help='Enable profiling support, see: http://werkzeug.pocoo.org/docs/contrib/profiler/')
    mode.add_argument('-l', '--lint', dest='linting', action="store_true",
                      help='Enable WSGI sanity checks, see: http://werkzeug.pocoo.org/docs/contrib/lint/')

    args = parser.parse_args()

    if args.profiling:
        from werkzeug.contrib.profiler import ProfilerMiddleware
        app.wsgi_app = ProfilerMiddleware(app.wsgi_app)

    elif args.linting:
        from werkzeug.contrib.lint import LintMiddleware
        app.wsgi_app = LintMiddleware(app.wsgi_app)

    app.run(host=args.host, port=args.port)
